### ISSUE TITLE
download button

### ISSUE THREAD

**Issue by karissa** [datproject/dat.land#115]
working on this on the `download` branch

**Comment by maxogden** [comment]
idea for downloading huge files:

since the `window.saveAs` buffers the entire file into memory, causing large files to crash the tab, a workaround would be to use a service worker to download the file using webrtc/http and then proxy that into a local http download. so to the user it appears as a standard download in their download manager UI, as opposed to now where it buffers into memory with no progress UI provided by the browser and then saves all at once

**Comment by karissa** [comment]
moving to https://github.com/datproject/dat.land-roadmap/issues/31
