### ISSUE TITLE
Support datapackage.json

### ISSUE THREAD

**Issue by clkao** [datproject/dat.land#236]
Once #216 is done, we should also support reading metadata from datapackage.json

**Comment by juliangruber** [comment]
what's the difference between dat.json and datapackage.json?

**Comment by karissa** [comment]
nothing right now

**Comment by karissa** [comment]
just the name :P

**Comment by juliangruber** [comment]
so do we want two standards?

**Comment by karissa** [comment]
We are about to come to a point where we should probably have a standard and promote it. We could just encourage people to use dat.json and support datapackage.json only quietly for author/title. I imagine having our own standard like dat.json will be necessary because we may have some custom fields

**Comment by juliangruber** [comment]
i created a repo for us to work on the spec here: https://github.com/juliangruber/dat.json
